require:
  - rubocop-performance

# RuboCop 基本設定ファイル

# レイアウトに関連するルール
Layout/LineLength:
  Max: 120 # 1行の最大文字数を 120 に設定（デフォルトは80）

Layout/EndOfLine:
  EnforcedStyle: lf # 改行コードを LF に統一

# メトリクス（複雑さやブロック長）関連ルール
Metrics/BlockLength:
  Max: 50 # ブロック長の最大を 50 行に設定
  Exclude:
    - 'spec/**/*' # テストファイルでは無視

Metrics/MethodLength:
  Enabled: false # メソッドの長さ制限を無効化

Metrics/ClassLength:
  Enabled: false # クラスの長さ制限を無効化

Metrics/AbcSize:
  Enabled: false # メソッドの ABC サイズ制限を無効化

# スタイル（スタイルチェックのルール）
Style/Documentation:
  Enabled: false # トップレベルのドキュメントコメントを無効化

Style/FrozenStringLiteralComment:
  Enabled: true # `# frozen_string_literal: true` のコメントは有効

Style/StringLiterals:
  EnforcedStyle: single_quotes # 文字列リテラルはシングルクオートを推奨

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma # 配列の末尾カンマを統一

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma # ハッシュの末尾カンマを統一

# Lint（明確なバグの可能性を指摘）
Lint/AmbiguousBlockAssociation:
  Enabled: true # 曖昧なブロックの関連付けを警告

Lint/UselessAssignment:
  Enabled: true # 使用されていない変数代入を警告

Lint/UnusedMethodArgument:
  Enabled: true # 未使用のメソッド引数を警告

# Performance（パフォーマンス関連のルール）
Performance/RedundantMerge:
  Enabled: true # 冗長なマージ操作を警告

Performance/Detect:
  Enabled: true # 冗長な検出処理を警告

# プロジェクト固有の除外
AllCops:
  TargetRubyVersion: 3.0 # プロジェクトで使用する Ruby のバージョン
  Exclude:
    - 'db/schema.rb' # Rails の自動生成ファイルを除外
    - 'bin/**/*'     # bin ディレクトリを除外
    - 'node_modules/**/*' # node_modules を除外
