require:
  - rubocop-performance

# 全体設定
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'db/schema.rb'        # Rails の自動生成ファイル
    - 'bin/**/*'            # bin ディレクトリ
    - 'node_modules/**/*'   # Node.js の依存ファイル

# Layout（レイアウト関連）
Layout/LineEndStringConcatenationIndentation:
  Enabled: false # デファクトスタンダード外のため無効化

# Lint（潜在的なバグや非推奨コードの警告）
Lint/AmbiguousOperatorPrecedence:
  Enabled: true
Lint/AmbiguousRange:
  Enabled: true
Lint/ConstantOverwrittenInRescue:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateMatchPattern:
  Enabled: true
Lint/DuplicateSetElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: false # デファクトでは許容されることが多いため無効化
Lint/EmptyClass:
  Enabled: false # 無効化（用途によって許容されるため）
Lint/ItWithoutArgumentsInBlock:
  Enabled: false # テストでは短い形式を好む場合が多い

# Metrics（コードの複雑性や長さに関するルール）
Metrics/BlockLength:
  Max: 50 # ブロックの長さを緩和
  Exclude:
    - 'spec/**/*' # テストコードは除外

Metrics/MethodLength:
  Max: 20 # メソッドの長さを緩和
  Enabled: true

Metrics/ClassLength:
  Max: 300 # クラスの長さを緩和
  Enabled: true

Metrics/ModuleLength:
  Max: 400 # モジュールの長さを緩和
  Enabled: true

Metrics/AbcSize:
  Enabled: false # ABC サイズの制限を無効化

# Naming（命名規則）
Naming/BlockForwarding:
  Enabled: true

# Security（セキュリティ関連）
Security/CompoundHash:
  Enabled: true
Security/IoMethods:
  Enabled: true

# Style（コードスタイル）
Style/ArgumentsForwarding:
  Enabled: true
Style/DataInheritance:
  Enabled: true
Style/FileRead:
  Enabled: true
Style/MagicCommentFormat:
  Enabled: true
Style/StringChars:
  Enabled: true

# Performance（パフォーマンス関連）
Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/RedundantEqualityComparisonBlock:
  Enabled: true
